site_name: Τεχνική Στήριξη ΣΕΠΕΗΥ

theme:
  name: material
  language: gr
  features:
    - navigation.indexes
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Αλλαγή σε σκούρο θέμα
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Αλλαγή σε ανοιχτό θέμα

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify

plugins:
  - git-revision-date
  - search

repo_url: https://github.com/pe86/linux
edit_uri: edit/main/docs
strict: true
