# copyright: Copyright © 2000-2021 the <a href="https://github.com/ltsp/ltsp/graphs/contributors">LTSP developers</a>
edit_uri: edit/main/docs
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.keys
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
      title: Περιεχόμενα σελίδας
plugins:
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        test.md: index.md
  - search
  - with-pdf:
      author: Έκδοση pdf του https://ts.sch.gr/wiki/Linux
      copyright: Copyright © 2008-2021 Τεχνική Στήριξη ΣΕΠΕΗΥ
      cover_title: ΣΕΠΕΗΥ με Linux
      cover_subtitle: Ubuntu 20.04/LTSP/Epoptes/sch-scripts
      enabled_if_env: ENABLE_PDF_EXPORT
      output_path: linux.pdf
repo_url: https://github.com/pe86/linux
site_name: Τεχνική Στήριξη ΣΕΠΕΗΥ
strict: false
theme:
# favicon: favicon.ico
  features:
    - navigation.indexes
  language: gr
# logo: logo-icon.png
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Αλλαγή σε σκούρο θέμα
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Αλλαγή σε ανοιχτό θέμα
