edit_uri: edit/main/docs
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.keys
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
      title: Περιεχόμενα σελίδας
plugins:
  - minify:
      minify_html: false
  - search
  - with-pdf:
      author: Έκδοση pdf του https://ts.sch.gr/docs/linux
      copyright: Copyright © 2008-2021 Τεχνική Στήριξη ΣΕΠΕΗΥ
      cover_title: ΣΕΠΕΗΥ με Linux
      cover_subtitle: Ubuntu 20.04/LTSP/Epoptes/sch-scripts
      enabled_if_env: ENABLE_PDF_EXPORT
      output_path: linux.pdf
repo_url: https://github.com/pe86/linux
site_name: Τεχνική Στήριξη ΣΕΠΕΗΥ
site_url: https://ts.sch.gr/docs/linux
strict: false
theme:
# favicon: favicon.ico
  features:
    - todo-navigation.indexes
    - todo-navigation.instant
  language: el
# logo: logo-icon.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Αλλαγή σε σκούρο θέμα
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Αλλαγή σε ανοιχτό θέμα
nav:
  - index.md
  - Ubuntu:
    - ubuntu/index.md
    - ubuntu/download.md
    - liveusb/index.md
    - Εγκατάσταση:
      - ubuntu/install.md
      - ubuntu/disk-empty/index.md
      - ubuntu/disk-windows/index.md
      - ubuntu/disk-linux/index.md
    - repositories/index.md
    - software/index.md
  - LTSP:
    - Προετοιμασία:
      - ltsp/Αρχιτεκτονική.md
      - ltsp/Απαιτήσεις.md
      - ltsp/Πλεονεκτήματα.md
      - ltsp/Μειονεκτήματα.md
    - Εγκατάσταση: ltsp/index.md
    - Ρύθμιση clients:
      - ltsp/Εκκίνηση_από_το_δίκτυο/index.md
      - ltsp/Εκκίνηση_από_το_δίκτυο/Win32-loader.md
    - 'Αντιμετώπιση προβλημάτων': ltsp/FAQ.md
    - Προχωρημένα:
      - ltsp/Προχωρημένα/index.md
      - ltsp/Προχωρημένα/Αυτόματη_σύνδεση.md
      - ltsp/Προχωρημένα/Εκτυπωτές.md
      - ltsp/Προχωρημένα/Πολλά_εργαστήρια.md
      - ltsp/Προχωρημένα/Σαρωτές.md
      - ltsp/Προχωρημένα/Στατικά_hostnames.md
      - ltsp/Προχωρημένα/Χάρτης.md
  - Διαχείριση ΣΕΠΕΗΥ:
    - sch-scripts/index.md
    - sch-scripts/Αρχεία_ρυθμίσεων.md
    - sch-scripts/Βοήθεια.md
    - sch-scripts/Δημοσίευση_εικονικού_δίσκου.md
    - sch-scripts/Δικαιώματα_καταλόγων.md
    - sch-scripts/Εγκατάσταση.md
    - sch-scripts/Εκκίνηση_της_εφαρμογής.md
    - sch-scripts/Εντολές_ltsp.md
    - sch-scripts/Κοινόχρηστοι_κατάλογοι.md
    - sch-scripts/Ρύθμιση_σύνδεσης_δικτύου.md
    - sch-scripts/Συντήρηση_ΣΕΠΕΗΥ.md
    - sch-scripts/Τμήματα.md
    - sch-scripts/Χρήστες/index.md
    - sch-scripts/Χρήστες/Δημιουργία_χρηστών.md
    - sch-scripts/Χρήστες/Διαγραφή_χρηστών.md
    - sch-scripts/Χρήστες/Εκτέλεση_εντολών.md
    - sch-scripts/Χρήστες/Επεξεργασία_χρηστών.md
  - Επόπτης:
    - epoptes/index.md
    - epoptes/Βοήθεια.md
    - epoptes/Δημιουργία_τάξης.md
    - epoptes/Διαδραστική_εκπαίδευση.md
    - epoptes/Διαχείριση_υπολογιστών.md
    - epoptes/Εγκατάσταση.md
    - epoptes/Είσοδος_χρηστών.md
    - epoptes/Εκκίνηση_εφαρμογής.md
    - epoptes/Ετικέτες.md
  - Εφαρμογές:
    - alice/index.md
    - appinventor/index.md
    - arduino/index.md
    - gamemaker/index.md
    - gparted/index.md
    - java/index.md
    - lamp/index.md
    - lamp/phpMyAdmin.md
    - mate-system-monitor/index.md
    - sch-webapp-launcher/index.md
  - Προχωρημένα:
    - advanced/index.md
    - advanced/kernel.md
    - advanced/Αναβάθμιση.md
    - advanced/Απομακρυσμένη_πρόσβαση.md
    - advanced/Έλεγχος_συμβατότητας.md
    - advanced/Περιοδικές_εργασίες.md
    - advanced/Περιφερειακά/index.md
    - advanced/Περιφερειακά/UPS.md
    - advanced/Περιφερειακά/Διαδραστικοί.md
    - advanced/Περιφερειακά/Εκτυπωτές.md
    - advanced/Περιφερειακά/Κάμερες.md
    - advanced/Περιφερειακά/Σαρωτές.md
    - advanced/contributing.md
    - TODO.md
  - support/index.md
