edit_uri: edit/main/docs
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.keys
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
      title: Περιεχόμενα σελίδας
plugins:
  - minify:
      minify_html: false
  - search
  - section-index
  - with-pdf:
      author: Έκδοση pdf του https://ts.sch.gr/docs/linux
      copyright: Copyright © 2008-2021 Τεχνική Στήριξη ΣΕΠΕΗΥ
      cover_title: ΣΕΠΕΗΥ με Linux
      cover_subtitle: Ubuntu 20.04/LTSP/Epoptes/sch-scripts
      enabled_if_env: ENABLE_PDF_EXPORT
      output_path: linux.pdf
repo_url: https://github.com/pe86/linux
site_name: Τεχνική Στήριξη ΣΕΠΕΗΥ
site_url: https://ts.sch.gr/docs/linux
strict: false
theme:
# favicon: favicon.ico
  features:
    - todo-navigation.indexes
    - todo-navigation.instant
  language: el
# logo: logo-icon.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Αλλαγή σε σκούρο θέμα
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Αλλαγή σε ανοιχτό θέμα
nav:
  - index.md
  - Ubuntu:
    - ubuntu/index.md
    - ubuntu/download.md
    - liveusb/index.md
    - Εγκατάσταση:
      - ubuntu/installation.md
      - ubuntu/disk-empty.md
      - ubuntu/disk-windows.md
      - ubuntu/disk-linux.md
    - repositories/index.md
    - software/index.md
  - LTSP:
    - ltsp/index.md
    - ltsp/advantages.md
    - ltsp/disadvantages.md
    - ltsp/requirements.md
    - ltsp/installation.md
    - Ρύθμιση clients:
      - ltsp/netboot.md
      - ltsp/win32-loader.md
    - ltsp/faq.md
    - Προχωρημένα:
      - ltsp/advanced/index.md
      - ltsp/advanced/autologin.md
      - ltsp/advanced/printers.md
      - ltsp/advanced/multiple-labs.md
      - ltsp/advanced/scanners.md
      - ltsp/advanced/hostnames.md
      - ltsp/advanced/map.md
  - Διαχείριση ΣΕΠΕΗΥ:
    - sch-scripts/index.md
    - sch-scripts/Αρχεία_ρυθμίσεων.md
    - sch-scripts/Βοήθεια.md
    - sch-scripts/Δημοσίευση_εικονικού_δίσκου.md
    - sch-scripts/Δικαιώματα_καταλόγων.md
    - sch-scripts/Εγκατάσταση.md
    - sch-scripts/Εκκίνηση_της_εφαρμογής.md
    - sch-scripts/Εντολές_LTSP.md
    - sch-scripts/Κοινόχρηστοι_κατάλογοι.md
    - sch-scripts/Ρύθμιση_σύνδεσης_δικτύου.md
    - sch-scripts/Συντήρηση_ΣΕΠΕΗΥ.md
    - sch-scripts/Τμήματα.md
    - sch-scripts/Χρήστες/index.md
    - sch-scripts/Χρήστες/Δημιουργία_χρηστών.md
    - sch-scripts/Χρήστες/Διαγραφή_χρηστών.md
    - sch-scripts/Χρήστες/Εκτέλεση_εντολών.md
    - sch-scripts/Χρήστες/Επεξεργασία_χρηστών.md
  - Επόπτης:
    - epoptes/index.md
    - epoptes/installation.md
    - epoptes/usage.md
    - epoptes/groups.md
    - epoptes/lan-benchmark.md
    - epoptes/on-ltsp-client.md
  - Εφαρμογές:
    - alice/index.md
    - appinventor/index.md
    - arduino/index.md
    - gamemaker/index.md
    - gparted/index.md
    - java/index.md
    - lamp-server/index.md
    - phpmyadmin/index.md
    - mate-system-monitor/index.md
    - sch-webapp-launcher/index.md
  - Προχωρημένα:
    - advanced/index.md
    - advanced/remote-access.md
    - advanced/smartboards.md
    - advanced/compatibility.md
    - advanced/clean-upgrade.md
    - advanced/kernels.md
    - advanced/contributing.md
  - support/index.md
