edit_uri: edit/main/docs
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
plugins:
  - git-revision-date
  - search
repo_url: https://github.com/pe86/linux
site_name: Τεχνική Στήριξη ΣΕΠΕΗΥ
strict: true
theme:
  features:
    - navigation.indexes
    - navigation.instant
  language: gr
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Αλλαγή σε σκούρο θέμα
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Αλλαγή σε ανοιχτό θέμα
