site_name: Τεχνική Στήριξη ΣΕΠΕΗΥ

theme:
  name: material
  language: gr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - git-revision-date

repo_url: https://github.com/pe86/linux
edit_uri: edit/main/docs
strict: true
